// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10C11z4BB3Cz5hjVn45wgkiDMFccougM',
    appId: '1:90115821420:android:d7d39b12b9478a53f12d49',
    messagingSenderId: '90115821420',
    projectId: 'fir-auth-89014',
    storageBucket: 'fir-auth-89014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoVHptMP9A6nK-YF0udhsMGmLsqlvLmM',
    appId: '1:90115821420:ios:bf63d2c9fdb7cddef12d49',
    messagingSenderId: '90115821420',
    projectId: 'fir-auth-89014',
    storageBucket: 'fir-auth-89014.appspot.com',
    iosClientId: '90115821420-5fpc69ms2j8012q5hei3bgce6mrhrrc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoVHptMP9A6nK-YF0udhsMGmLsqlvLmM',
    appId: '1:90115821420:ios:f85a69dc57fb3a18f12d49',
    messagingSenderId: '90115821420',
    projectId: 'fir-auth-89014',
    storageBucket: 'fir-auth-89014.appspot.com',
    iosClientId: '90115821420-skk3id2s71b8bif0i8v3n9858n3vl8ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
